#define SCREEN_W 1024
#define SCREEN_H 576
#define FPS 50

// Scene
#define SCENE_TITLE_THECAMELOT_W 410
#define SCENE_TITLE_THECAMELOT_H 410
#define SCENE_TITLE_PLAY_W 512
#define SCENE_TITLE_PLAY_H 100
#define SCENE_TITLE_SETTING_W 256
#define SCENE_TITLE_SETTING_H 90
#define SCENE_TITLE_EXIT_W 768
#define SCENE_TITLE_EXIT_H 90

// Splash