#define SCREEN_W 1024
#define SCREEN_H 576
#define FPS 50
#define MONSTER_APPEAR -50

// troll
#define NAME_PLIST_TROLL_ATK "images/TROLL/ATTACK/1_TROLL_ATTACK.plist"
#define NAME_PNG_TROLL_ATK "ATTAK_00%d.png"
#define COUNT_IMG_TROLL_ATK 7

#define NAME_SPRITE_TROLL "CloseNormal.png"

#define NAME_PLIST_TROLL_DIE "images/TROLL/DIE/1_TROLL_DIE.plist"
#define NAME_PNG_TROLL_DIE "DIE_00%d.png"
#define COUNT_IMG_TROLL_DIE 7

#define NAME_PLIST_TROLL_WALK "images/TROLL/WALK/1_TROLL_WALK.plist"
#define NAME_PNG_TROLL_WALK "WALK_00%d.png"
#define COUNT_IMG_TROLL_WALK 7

//ARCHER

#define NAME_PLIST_ARCHER_ATTACK "images/ARCHER/ATTACK/1_TROLL_ATTACK.plist"
#define NAME_PNG_ARCHER_ATTACK "ATTACK_00%d.png"
#define COUNT_IMG_ARCHER_ATTACK 5

#define NAME_SPRITE_ARCHER "images/ARCHER/ATTACK/ATTACK_1.png"

#define NAME_PLIST_ARCHER_DIE "images/ARCHER/DIE/1_TROLL_DIE.plist"
#define NAME_PNG_ARCHER_DIE "DIE_00%d.png"
#define COUNT_IMG_ARCHER_DIE 5

#define IMG_Weapons "images/ARCHER/ATTACK/ATTACK_Arrow.png"

// Hammer Troll
#define NAME_PLIST_HAMMERTROLL_ATK "images/TROLL/ATTACK/2_TROLL_ATTACK.plist"
#define NAME_PNG_HAMMERTROLL_ATK "2_ATTAK_00%d.png"
#define COUNT_IMG_HAMMERTROLL_ATK 7

#define NAME_SPRITE_HAMMERTROLL "CloseNormal.png"

#define NAME_PLIST_HAMMERTROLL_DIE "images/TROLL/DIE/2_TROLL_DIE.plist"
#define NAME_PNG_HAMMERTROLL_DIE "2_DIE_00%d.png"
#define COUNT_IMG_HAMMERTROLL_DIE 7

#define NAME_PLIST_HAMMERTROLL_WALK "images/TROLL/WALK/2_TROLL_WALK.plist"
#define NAME_PNG_HAMMERTROLL_WALK "2_WALK_00%d.png"
#define COUNT_IMG_HAMMERTROLL_WALK 7

// Bone Troll 
#define NAME_PLIST_BONETROLL_ATK "images/TROLL/ATTACK/3_TROLL_ATTACK.plist"
#define NAME_PNG_BONETROLL_ATK "3_ATTAK_00%d.png"
#define COUNT_IMG_BONETROLL_ATK 7

#define NAME_SPRITE_BONETROLL "CloseNormal.png"

#define NAME_PLIST_BONETROLL_DIE "images/TROLL/DIE/3_TROLL_DIE.plist"
#define NAME_PNG_BONETROLL_DIE "3_DIE_00%d.png"
#define COUNT_IMG_BONETROLL_DIE 7

#define NAME_PLIST_BONETROLL_WALK "images/TROLL/WALK/3_TROLL_WALK.plist"
#define NAME_PNG_BONETROLL_WALK "3_WALK_00%d.png"
#define COUNT_IMG_BONETROLL_WALK 7

// Hammer Ork
#define NAME_PLIST_HAMMERORK_ATK "images/1_ORK/1_ORK_ATTACK.plist"
#define NAME_PNG_HAMMERORK_ATK "1_ORK_ATTACK_00%d.png"
#define COUNT_IMG_HAMMERORK_ATK 7

#define NAME_SPRITE_HAMMERORK "CloseNormal.png"

#define NAME_PLIST_HAMMERORK_DIE "images/1_ORK/1_ORK_DIE.plist"
#define NAME_PNG_HAMMERORK_DIE "1_ORK_DIE_00%d.png"
#define COUNT_IMG_HAMMERORK_DIE 7

#define NAME_PLIST_HAMMERORK_WALK "images/1_ORK/1_ORK_WALK.plist"
#define NAME_PNG_HAMMERORK_WALK "1_ORK_WALK_00%d.png"
#define COUNT_IMG_HAMMERORK_WALK 7